services:
  myapp-main:
    image: josephgallant/golftournamentapp:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/golf_club_tournaments_db_2025
      - spring.datasource.password=Keyin2024
      - spring.datasource.username=root